---
- name: Configure icap on Cisco Catalyst Center
  hosts: localhost
  vars_files:
    - "credentials.yml"
  connection: local
  gather_facts: no
  tasks:
    - name: assurance settings
      cisco.dnac.assurance_icap_settings_workflow_manager:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
        dnac_log: True
        dnac_log_level: DEBUG
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: merged
        config_verify: True
        config:
          - assurance_icap_settings:
                - capture_type: onboarding
                  duration_in_mins: 30
                  client_mac: client_mac_id  #required field
                  wlc_id: wlc_id  #required field
                  ap_id: ap_id  #required field
                  slot:
                    - 1
                    - 2
                  ota_band: 5GHz
                  ota_channel: 36
                  ota_channel_width: 20
                  deploy: false
                  generates_the_device_cli: false

            