- hosts: dnac_servers
  vars_files:
    - credentials.yml
  gather_facts: no
  connection: local
  tasks:
    - name: Create global pool, reserve subpool and network functions
      cisco.dnac.network_settings_workflow_manager:
        dnac_host: "{{ dnac_host }}"
        dnac_port: "{{ dnac_port }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: True
        dnac_log_level: DEBUG
        dnac_log_append: True
        # dnac_log_file_path: "{{ dnac_log_file_path }}"
        state: merged
        config_verify: True
        config:
        - network_management_details:
          - site_name: Global/Hyderabad
            settings:
              # network_aaa: #works only if we system settigns is set
              #   primary_server_address: 10.0.0.20 #Mandatory for AAA and ISE
              #   secondary_server_address: 10.0.0.21
              #   protocol: TACACS
              #   server_type: AAA
              #   # shared_secret: string #ISE
              # client_and_endpoint_aaa: #works only if we system settigns is set
              #   primary_server_address: 10.197.156.42 #Mandatory for AAA and ISE
              #   secondary_server_address: 10.0.0.21
              #   protocol: RADIUS                                     
              #   server_type: AAA
              #   shared_secret: string #ISE
              # dhcp_server:
              # - 10.0.0.1
              # dns_server:
              #   domain_name: cisco.com
              #   primary_ip_address: 10.0.0.2
              #   secondary_ip_address: 10.0.0.3
              # ntp_server:
              # - 10.0.0.4
              # timezone: GMT
              # message_of_the_day:
              #   banner_message: hello
              #   retain_existing_banner: True
              wired_data_collection:
                enable_wired_data_collection: true
              wireless_telemetry:
                enable_wireless_telemetry: false
              # netflow_collector:
              #   # collector_type: Telemetry_broker_or_UDP_director
              #   # ip_address: 10.0.0.6
              #   # port: 444
              #   enable_on_wired_access_devices: true
              snmp_server:
                configure_dnac_ip: false
                ip_addresses:
                - 10.0.0.5
              # syslog_server:
              #   configure_dnac_ip: false
              #   ip_addresses:
              #   - 10.0.0.7
