- hosts: dnac_servers
  vars_files:
    - credentials.yml
  gather_facts: no
  connection: local
  tasks:
    - name: Create global pool, reserve subpool and network functions
      cisco.dnac.network_settings_workflow_manager:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: merged
        config_verify: true
        config:
          - global_pool_details:
              settings:
                ip_pool:
                  - cidr: 40.40.32.0/24
                    dhcp_server_ips:
                      - 204.192.9.40
                    dns_server_ips:
                      - 171.70.168.183
                    gateway: 40.40.32.1
                    ip_address_space: IPv4
                    name: IPPOOLLLLLIPPOOLLLLLIPPOOLLLLLIPPOOLLLLLIPPOOLLLLLIPPOOLLLLLIPPOOLLLLLIPPOOLLLLLI
                    pool_type: Generic
                    # prev_name: assurance
                  # - cidr: 40.40.32.0/24
                  #   dhcp_server_ips:
                  #     - 204.192.8.40
                  #   dns_server_ips:
                  #     - 171.70.168.183
                  #   gateway: 40.40.32.1
                  #   ip_address_space: IPv4
                  #   name: IPPOOLLLLLIPPOOLLLLLIPPOOLLLLLIPPOOLLLLLIPPOOLLLLLIPPOOLLLLLIPPOOLLLLLIPPOOLLLLLIPPPPPPPPPPPPPPPPPPPPPPP2
                  #   pool_type: Generic
                  # - cidr: 40.40.32.0/24
                  #   dhcp_server_ips:
                  #     - 204.192.10.40
                  #   dns_server_ips:
                  #     - 171.70.168.183
                  #   gateway: 40.40.32.1
                  #   ip_address_space: IPv4
                  #   name: IPPOOLLLLLIPPOOLLLLLIPPOOLLLLLIPPOOLLLLLIPPOOLLLLLIPPOOLLLLLIPPOOLLLLLIPPOOLLLLLIPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP3
                  #   pool_type: Generic
